#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2015 OpenWrt.org

. $IPKG_INSTROOT/lib/functions/olsrd.sh

START=65
USE_PROCD=1
CONF=/var/etc/olsrd6.conf

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/olsrd -f $CONF -nofork
	procd_set_param respawn
	procd_set_param file $CONF  # automatically restart olsrd6 if cfg has changed
	procd_close_instance

	olsrd_setup_smartgw_rules
}
