#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@olsrd2[-1]
	add ucitrack olsrd2
	set ucitrack.@olsrd2[-1].init=olsrd2
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
rm -f /tmp/luci-modulecache/*

exit 0
